<page title="Interiors Home Events | Exciting Furniture Shopping Experience | Harrisburg and Lancaster PA" />
<metadata name="description" content="INTERIORS Home is Central PA's most exciting furniture shopping experience, offering a wide selection of fashionable home furnishings at guaranteed low prices and free award-winning design service." />
<!-- Static Page -->
<div class="grid-container special-promo-container">
        <div class="grid-50 tablet-grid-50 push-25">
            <img src="/css/71/images/event/summer-1.jpg" alt="Summer" class="top-space-15px" />
        </div>
        <div class="clear"></div>
        <div class="grid-50 tablet-grid-50">
            <img src="/css/71/images/event/summer-2.jpg" style="width: 104%;" alt="Summer" class="top-space-15px" />
        </div>

        <div class="grid-50 tablet-grid-50">
            <img src="/css/71/images/event/summer-3.jpg" style="width: 104%;" alt="Summer" class="top-space-15px" />
        </div>
        <div class="clear"></div>
        <div class="grid-90 tablet-grid-90 push-5">
            <img src="/css/71/images/event/summer-4.jpg" alt="Summer" class="top-space-15px" />
        </div>
        <div class="clear"></div>
        <div class="grid-30 tablet-grid-30">
            <img src="/css/71/images/event/summer-5.jpg" alt="Summer" class="top-space-15px" />
        </div>

        <div class="grid-70 tablet-grid-70">
            <img src="/css/71/images/event/summer-6.jpg" alt="Summer" class="top-space-15px" />
        </div>
        <div class="clear"></div>
        <div class="grid-90 tablet-grid-90 push-5">
            <img src="/css/71/images/event/summer-7.jpg" alt="Summer" class="top-space-15px" />
        </div>
        <div class="clear"></div>
        <div class="grid-50 tablet-grid-50">
            <img src="/css/71/images/event/summer-8.jpg" alt="Summer" class="top-space-15px" />
        </div>

        <div class="grid-50 tablet-grid-50">
            <img src="/css/71/images/event/summer-9.jpg" alt="Summer" class="top-space-15px" />
        </div>
        <div class="clear"></div>
        <div class="grid-90 tablet-grid-90 push-5">
            <img src="/css/71/images/event/summer-10.jpg" alt="Summer" class="top-space-15px" />
        </div>
        <div class="clear"></div>
        <div class="grid-50 tablet-grid-50">
            <img src="/css/71/images/event/summer-11.jpg" style="width: 104%;" alt="Summer" class="top-space-15px" />
        </div>

        <div class="grid-50 tablet-grid-50">
            <img src="/css/71/images/event/summer-12.jpg" style="width: 104%;" alt="Summer" class="top-space-15px" />
        </div>
        <div class="clear"></div>
        <div class="grid-50 tablet-grid-50 push-25">
            <img src="/css/71/images/event/summer-13.jpg" alt="Summer" class="top-space-15px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100 event-browse">
            <a href="/summer-classics/brand-type.aspx">Browse >></a>
        </div>
        <div class="clear"></div>

</div>
<!-- End Static Page -->