<page title="Interiors Home Special Promotion | Exciting Furniture Shopping Experience | Harrisburg and Lancaster PA" />
<metadata name="description" content="INTERIORS Home is Central PA's most exciting furniture shopping experience, offering a wide selection of fashionable home furnishings at guaranteed low prices and free award-winning design service." />
<!-- Static Page -->
<div class="grid-container special-promo-container">
    <div class="hide-on-mobile">
        <div class="grid-40 tablet-grid-60">
            <img src="/css/71/images/stickley-promo/stickley-1.jpg" alt="Sink into Stickley" width="444" height="77" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-2.jpg" alt="Relaxation | Stickley" width="1140" height="741" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-3-4.jpg" alt="Stickley Spring Sale" width="1140" height="654" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-90 prefix-5">
            <img src="/css/71/images/stickley-promo/stickley-5.jpg" alt="Create Great Rooms" width="1024" height="167" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-6.jpg" alt="Stickley Living Room" width="1140" height="559" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-7-8-9-15.jpg" alt="Make it Yours!" width="1140" height="420" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-20 tablet-grid-33">
            <img src="/css/71/images/stickley-promo/stickley-10.jpg" alt="Step 1" width="212" height="333" class="top-space-15px" />
        </div>
        <div class="grid-20 tablet-grid-33">
            <img src="/css/71/images/stickley-promo/stickley-11.jpg" alt="Step 2" width="212" height="333" class="top-space-15px" />
        </div>
        <div class="grid-20 tablet-grid-33">
            <img src="/css/71/images/stickley-promo/stickley-12.jpg" alt="Step 3" width="212" height="333" class="top-space-15px" />
        </div>
        <div class="grid-20 tablet-grid-33">
            <img src="/css/71/images/stickley-promo/stickley-13.jpg" alt="Step 4" width="212" height="333" class="top-space-15px" />
        </div>
        <div class="grid-20 tablet-grid-33">
            <img src="/css/71/images/stickley-promo/stickley-14.jpg" alt="Step 5" width="212" height="333" class="top-space-15px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-18-19.jpg" alt="Largest Stickley Gallery in PA" width="1140" height="562" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-60 prefix-20 tablet-grid-80 tablet-prefix-10">
            <img src="/css/71/images/stickley-promo/stickley-16.jpg" alt="Save on Luxe Leather" width="676" height="155" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-17.jpg" alt="Stickley Leather" width="1140" height="563" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <!-- <div class="grid-70 prefix-15 tablet-grid-90 tablet-prefix-5">
            <img src="/css/71/images/stickley-promo/stickley-20.jpg" alt="Limited Time! - Ends March 22" width="792" height="80" class="top-space-50px" />
        </div>
        <div class="clear"></div> -->
        <div class="grid-100">
            <a href="https://view.publitas.com/interiors-home/interiors-home-stickley-spring-sale/" target="_blank">
                <img src="/css/71/images/stickley-promo/stickley-22-21.jpg" alt="Stickley Spring Sale | Browse the Catalog" width="1140" height="373" class="top-space-15px" />
            </a>
        </div>
        <div class="clear"></div>
    </div>


    <div class="hide-on-desktop hide-on-tablet">
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-1.jpg" alt="Sink into Stickley" width="707" height="122" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-2.jpg" alt="Relaxation | Stickley" width="707" height="460" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-3.jpg" alt="Stickley Spring Sale" width="707" height="811" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-4.jpg" alt="Largest Stickley Gallery in PA" width="707" height="811" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-5.jpg" alt="Create Great Rooms" width="707" height="115" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-6.jpg" alt="Stickley Living Room" width="707" height="347" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-7.jpg" alt="Make it Yours!" width="707" height="107" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-8-9.jpg" alt="Sectionals by Stickley" width="707" height="888" class="top-space-15px" />
        </div>
        <div class="clear"></div>
        <div class="mobile-grid-50">
            <img src="/css/71/images/stickley-promo/stickley-10.jpg" alt="Step 1" width="344" height="540" class="top-space-50px" />
        </div>
        <div class="mobile-grid-50">
            <img src="/css/71/images/stickley-promo/stickley-11.jpg" alt="Step 2" width="344" height="540" class="top-space-50px" />
        </div>
        <div class="mobile-grid-50">
            <img src="/css/71/images/stickley-promo/stickley-12.jpg" alt="Step 3" width="344" height="540" class="top-space-15px" />
        </div>
        <div class="mobile-grid-50">
            <img src="/css/71/images/stickley-promo/stickley-13.jpg" alt="Step 4" width="344" height="540" class="top-space-15px" />
        </div>
        <div class="mobile-grid-50">
            <img src="/css/71/images/stickley-promo/stickley-14.jpg" alt="Step 5" width="344" height="540" class="top-space-15px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-15.jpg" alt="Easy and Affordable!" width="707" height="723" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-16.jpg" alt="Save on Luxe Leather" width="707" height="162" class="top-space-15px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-17.jpg" alt="Stickley Leather" width="707" height="349" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-18.jpg" alt="Largest Stickley Gallery in PA" width="707" height="711" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-19.jpg" alt="Stickley Leather" width="707" height="700" class="top-space-50px" />
        </div>
        <div class="clear"></div>
        <!-- <div class="grid-100">
            <img src="/css/71/images/stickley-promo/stickley-20.jpg" alt="Limited Time! - Ends March 22" width="707" height="71" class="top-space-50px" />
        </div>
        <div class="clear"></div> -->
        <div class="grid-100">
            <a href="https://view.publitas.com/interiors-home/interiors-home-stickley-spring-sale/" target="_blank">
                <img src="/css/71/images/stickley-promo/stickley-21-22.jpg" alt="Browse the Catalog | Stickley Spring Sale" width="707" height="855" class="top-space-15px" />
            </a>
        </div>
        <div class="clear"></div>
    </div>
</div>
<!-- End Static Page -->