
Updated that I created for Noah's

<page title="Clearance Items | METADATA COMPANY | METADATA CITY, METADATA STATE"></page>
<metadata name="keywords" content="METADATA COMPANY Clearance Items, METADATA COMPANY Furniture Store, METADATA COMPANY Home Furnishings, Furniture Store, Home Furnishings, METADATA CITY, METADATA STATE METADATA ZIPCODE"></metadata>
<metadata name="description" content="METADATA COMPANY clearance items."></metadata>
<!-- Static Page -->
<div class="grid-container">
	<div class="grid-20 tablet-grid-20 hide-on-mobile">
		<include file="companyinfonav.inc"></include>
	</div>
	<div class="grid-80 tablet-grid-80">
		<div class="pagetitle">
			<h1>Clearance Items</h1>
		</div>
		<div id="staticpagecontent">
			<include file="CustomerContent/Clearance Items.inc"></include>
			<br />
			<br />
<!--TEMPLATE-->
		<!-- <div class="grid-50 tablet-grid-50 clearanceitemsection">
			<div class="clearanceitemimg">
				<img src="/css/20495/images/clearanceitems/" width="237" height="199" alt="Clearance Item" />
				<h2>SOLD</h2>
			</div>
			<div class="clearanceitemtext">
				<h2></h2>
				<p>Was $</p>
				<p>Now $</p>
			</div>
		</div>
		<div class="grid-50 tablet-grid-50 clearanceitemsection">
			<div class="clearanceitemimg">
				<img src="/css/20495/images/clearanceitems/" width="237" height="199" alt="Clearance Item" />
				<h2>SOLD</h2>
			</div>
			<div class="clearanceitemtext">
				<h2></h2>
				<p>Was $</p>
				<p>Now $</p>
			</div>
		</div> -->

		<div class="grid-50 tablet-grid-50 clearanceitemsection">
			<div class="clearanceitemimg">
				<img src="/css/20495/images/clearance-items/EmptyHomeBanner-237x199.jpg" width="237" height="199" alt="Clearance Item" />
				<!-- <span>SOLD!</span> -->
			</div>
			<div class="clearanceitemtext">
				<h2>Sample Clearance Item #1</h2>
				<p>Call for Pricing!</p>

			</div>
		</div>
		<div class="grid-50 tablet-grid-50 clearanceitemsection">
			<div class="clearanceitemimg">
				<img src="/css/20495/images/clearance-items/EmptyHomeBanner-237x199.jpg" width="237" height="199" alt="Clearance Item" />
				<span>SOLD!</span>
			</div>
			<div class="clearanceitemtext">
				<h2>Sample Clearance Item #2</h2>
				<p>Was $1,599</p>
				<p>Now $999</p>
			</div>
		</div>
		<div class="clear"></div>
		</div>
	</div>
	<div class="clear"></div>
</div>
<!-- End Static Page -->

<style>
.pagetitle { /* COMBINE WITH .homepagetext */
	/*font-family: 'Raleway', sans-serif;*/
	color: #2a2a2a;
	background-color: #F4F4F4;
	padding: 10px;
	margin: 30px 0 30px 0;
}

.pagetitle h1 {
	font-size: 22px;
}

.clearanceitemsection {
    text-align: center;
    margin-bottom: 20px;
}

.clearanceitemimg {
    position: relative;
    width: 237px;
    height: 199px;
    margin: 0 auto;
}

.clearanceitemtext h2 {
	margin: 10px 0 6px;
	font-weight: normal;
}

.clearanceitemtext p {
	font-size: 1.3em;
	font-weight: bold;
	color: #C30000;
}

.clearanceitemimg span {
    position: absolute;
    transform: translateX(-50%);
    top: 45%;
    left: 50%;
    font-size: 60px;
    font-weight: bold;
    color: red;
}
</style>

Old:
<page title="Save On Clearance Items | Site" />
<!-- Static Page -->
<div class="grid-container">
	<div class="grid-100">
		<div id="pagetitle">
			<h1>Clearance</h1>
		</div>

		<div class="grid-50 tablet-grid-50">
			<div id="staticpagecontent">
				<div class="grid-50 tablet-grid-50">
					<div class="clearanceimage">
						<img src="/css/1382/images/184450.jpg" alt="" />
					</div>
				</div>
				<div class="grid-50 tablet-grid-50">
					<div class="clearancetext">
						<h3>Item# 184450</h3>
						<p>Lancer Elegant Denim sofa</p>
						<br />
						<h3>Price: $1,199.00</h3>
						<h2>Clearance: $699.00</h2>
					</div>
				</div>
			</div>
		</div>

		<div class="grid-50 tablet-grid-50">
			<div id="staticpagecontent">
				<div class="grid-50 tablet-grid-50">
					<div class="clearanceimage">
						<img src="/css/1382/images/118971.jpg" alt="" />
					</div>
				</div>
				<div class="grid-50 tablet-grid-50">
					<div class="clearancetext">
						<h3>Item# 118971</h3>
						<p>Braxton Culler cream sofa</p>
						<br />
						<h3>Price: $1,639.00</h3>
						<h2>Clearance: $999.00</h2>
					</div>
				</div>
			</div>
		</div>

	</div>
	<div class="clear"></div>
</div>
<!-- End Static Page -->